raise ValueError(x => x)

x = 1